version: '3.7'

services:

  nuxt_dev:
    container_name: nuxt_dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/nuxt-app'
      - '/nuxt-app/node_modules'
    ports:
      - '3000:3000'
