FROM node:14.18.2-alpine

RUN mkdir -p /nuxt-app
WORKDIR /nuxt-app

COPY package.json .
RUN  npm config set registry https://registry.npm.taobao.org && \
     npm install

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

CMD [ "npm", "run", "dev" ]
