name: deploy docker image

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'

      - name: Build nuxt
        run: |
          npm install
          npm run build

      - name: Build the Docker image to tencentyun
        run: |
          docker login ccr.ccs.tencentyun.com -u=100016773380 -p=wang1234
          docker build -t nuxt-demo:latest .
          docker tag nuxt-demo:latest ccr.ccs.tencentyun.com/wangpf/nuxt-demo:latest
          docker push ccr.ccs.tencentyun.com/wangpf/nuxt-demo:latest

      - name: ssh login && run docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: cd /wangpf/nuxt-demo/ && sh docker-deploy.sh
